### ISSUE TITLE
[Feature Request] Add LICENSE

### ISSUE THREAD

**Issue by dfgHiatus** [dousha/PicoBridge#3]
I would like to use this to create a mod for [NeosVR](https://store.steampowered.com/app/740250/Neos_VR/), I figured this would be a good issue for future developers

**Comment by dousha** [comment]
Sorry for the late reply. Here's an update: we have contacted the PICO team about the licensing of the code (as one of the contributors has obtained critical documents directly from the PICO team). So far we haven't reached a satisfying conclusion on what license may be used. We will continue to negotiate with PICO. Hopefully, we can use a proper OSS license soon.
